services:
  mysql:
    image: mysql:latest
    ports: ["3306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

  redis:
    image: redis:alpine
    ports: ["6379:6379"]
    volumes:
      - ./testdata/dump.redis:/data/init-data.redis
    command: >
      sh -c "redis-server --save '' --appendonly no &
             sleep 2 &&
             redis-cli < /data/init-data.redis &&
             tail -f /dev/null"

  postgres:
    image: postgres:16
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./testdata/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  grpc-server:
    build: ./cmd/grpc
    ports: ["50051:50051"]

  # services for openapi testing
  petstore-api:
    image: swaggerapi/petstore3:latest
    ports:
      - "8091:8080"
    environment:
      SWAGGER_HOST: "http://localhost:8091"
      SWAGGER_BASE_PATH: "/api/v3"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v3/openapi.json"]
      interval: 30s
      timeout: 10s
      retries: 3

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8092:8080"
    environment:
      URLS_PRIMARY_NAME: "PetStore API"
      CONFIG_URL: "http://localhost:8091/api/v3/openapi.json"
    depends_on:
      petstore-api:
        condition: service_healthy
