// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountRowsSQLSource(arg1, arg2) {
  return window['go']['app']['App']['CountRowsSQLSource'](arg1, arg2);
}

export function Create(arg1, arg2) {
  return window['go']['app']['App']['Create'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['app']['App']['Delete'](arg1);
}

export function DescribeTableSQLSource(arg1, arg2) {
  return window['go']['app']['App']['DescribeTableSQLSource'](arg1, arg2);
}

export function Duplicate(arg1) {
  return window['go']['app']['App']['Duplicate'](arg1);
}

export function FetchSpecHTTPSource(arg1) {
  return window['go']['app']['App']['FetchSpecHTTPSource'](arg1);
}

export function GRPCMethods(arg1) {
  return window['go']['app']['App']['GRPCMethods'](arg1);
}

export function GRPCQueryFake(arg1, arg2) {
  return window['go']['app']['App']['GRPCQueryFake'](arg1, arg2);
}

export function GRPCQueryValidate(arg1, arg2, arg3) {
  return window['go']['app']['App']['GRPCQueryValidate'](arg1, arg2, arg3);
}

export function GenerateExampleRequestHTTPSource(arg1, arg2) {
  return window['go']['app']['App']['GenerateExampleRequestHTTPSource'](arg1, arg2);
}

export function Get(arg1) {
  return window['go']['app']['App']['Get'](arg1);
}

export function JQ(arg1, arg2) {
  return window['go']['app']['App']['JQ'](arg1, arg2);
}

export function List() {
  return window['go']['app']['App']['List']();
}

export function ListEndpointsHTTPSource(arg1) {
  return window['go']['app']['App']['ListEndpointsHTTPSource'](arg1);
}

export function ListTablesSQLSource(arg1) {
  return window['go']['app']['App']['ListTablesSQLSource'](arg1);
}

export function Perform(arg1) {
  return window['go']['app']['App']['Perform'](arg1);
}

export function PerformSQLSource(arg1, arg2) {
  return window['go']['app']['App']['PerformSQLSource'](arg1, arg2);
}

export function PerformVirtualEndpointHTTPSource(arg1, arg2, arg3) {
  return window['go']['app']['App']['PerformVirtualEndpointHTTPSource'](arg1, arg2, arg3);
}

export function Read(arg1) {
  return window['go']['app']['App']['Read'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['app']['App']['Rename'](arg1, arg2);
}

export function TestHTTPSource(arg1) {
  return window['go']['app']['App']['TestHTTPSource'](arg1);
}

export function TestSQLSource(arg1) {
  return window['go']['app']['App']['TestSQLSource'](arg1);
}

export function Update(arg1, arg2, arg3) {
  return window['go']['app']['App']['Update'](arg1, arg2, arg3);
}
